### ISSUE TITLE
GMT Timezone Difference

### ISSUE THREAD

**Issue by thomasfirnschrott** [southbridgeio/redmine_recurring_tasks#49]
I installed the plugin in the sameersbn/redmine container which works fine, 
just to let others know, since cron is not available in the official redmine image.

One problem still exists: 
The schedule's time seems to be GMT so all scheduled issues are created at selected time in GMT, which renders to be something else on the surface.

Is there a way to configure this?

**Comment by joho1968** [comment]
As a follow-up, the server is running with one TZ (the location of the actual server), and Redmine is running with another TZ (the location of most users). When a "time" is evaluated by the code, which one is used if the recurring task is set to execute at 14:00?

**Comment by olemskoi** [comment]
Please try the latest version.

**Comment by thomasfirnschrott** [comment]
I've upgraded to 0.3.3 but still I have the same issue.
If I schedule 10.00am a new ticket will be created to display last change at 11.00am on the frontend viewed by a user with Vienna time set.
