### ISSUE TITLE
Translation german, de

### ISSUE THREAD

**Issue by thomasfirnschrott** [southbridgeio/redmine_recurring_tasks#50]
May I contribute in adding a german translation.
Do you have guidelines or shall I just translate the en.yml out of conf folder and give it back to you?

What exactly needs to be configured to activate the localization?
Or is there a translation that I don't know of.

**Comment by joho1968** [comment]
Same question from me, but for Swedish

**Comment by funk-yourself** [comment]
Hi! Translation contributions are highly appreciated. Just make a PR with translated _lang_.yml file
#57 is a good example

**Comment by olemskoi** [comment]
Thank you!
