### ISSUE TITLE
Schedule section not appearing on issues

### ISSUE THREAD

**Issue by dboresjo** [southbridgeio/redmine_recurring_tasks#59]
Followed the installation instructions and enabled the "Redmine Recurring Tasks" for a project. The promised "schedule" section is not appearing on any tickets.

Environment:

-   Redmine version:           4.0.5.stable
-   Ruby version:                 2.5.1-p57 (2018-03-29) [x86_64-linux-gnu]
-   Rails version:                  5.2.3
-   Database adapter:          PostgreSQL

Redmine plugins:

-   redmine_recurring_tasks:  0.3.3

**Comment by olemskoi** [comment]
Did you enable restrictions in Role configuration?

**Comment by dboresjo** [comment]
Yes I enabled both view schedule and manage schedule.

**Comment by olemskoi** [comment]
Did you enable it in projects Modules section?

**Comment by dboresjo** [comment]
Yes I enabled "Redmine Recurring Tasks" in projects/<name>/settings/info, modules section

**Comment by olemskoi** [comment]
Can you please send screenshot of the task?

**Comment by dboresjo** [comment]
Here are the screenshots (watchers blurred out for privacy)
![New issue](https://user-images.githubusercontent.com/6451217/68288814-04395680-007d-11ea-9bf4-9bfcfaf06c70.png)
![Project Settings](https://user-images.githubusercontent.com/6451217/68288815-04395680-007d-11ea-9486-786b2a263e3a.png)

**Comment by olemskoi** [comment]
Please send tasks screenshot not in edit mode.

**Comment by dboresjo** [comment]
Aha! Now I see it. We were expecting to edit this setting in edit mode.

Thanks for your help.
